import { MoodMap } from '../types/mood';

const MOODS: MoodMap = {
  anxious: {
    id: 'anxious',
    poeticName: 'Static in the Chest',
    symbol: '⟳',
    tagline: 'constant, electric, close',
    lines: [
      'Everything is humming a little too loudly.',
      'Your hands know something the rest of you doesn\'t.',
      'The room is the same size it was. Isn\'t it.',
      'There are seventeen tabs open. The important one is not among them.',
      'The sentence keeps starting over before it finishes.',
      'Something is about to happen. Or it already did and you missed it.',
    ],
    emotionalMetric: {
      label: 'Pressure',
      stages: [
        '94° volatile',
        '78° building',
        '61° easing slightly',
        '48° finding ground',
      ],
    },
    colors: {
      primary: '#00E5A0',
      secondary: '#00CFBB',
      accent: '#B4FF91',
      bg: '#030f0a',
      text: '#C0F0DC',
      muted: 'rgba(192,240,220,0.5)',
      glow: 'rgba(0,229,160,0.3)',
      cardBg: 'rgba(0,229,160,0.06)',
      cardBorder: 'rgba(0,229,160,0.2)',
      dropdownBg: 'rgba(3,15,10,0.96)',
    },
    typography: {
      fontFamily: "'DM Mono', monospace",
      weight: 400,
      letterSpacing: '0.02em',
      lineHeight: '1.5',
      style: 'normal',
    },
    interaction: {
      transitionDuration: 200,
      borderRadius: '4px',
      spacing: 'tight',
      cursorStyle: 'jitter',
      textAnimation: 'fragment',
      soundHook: 'white-noise-low',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'volatile', intensity: 1.0 },
      { duration: 30, atmosphericLabel: 'building', intensity: 0.85 },
      { duration: 90, atmosphericLabel: 'easing', intensity: 0.65 },
      { duration: 180, atmosphericLabel: 'finding ground', intensity: 0.45 },
    ],
    playlist: [
      { title: 'Breathe (2 AM)', artist: 'Anna Nalick', url: 'https://www.youtube.com/watch?v=PiGBu29RbcM' },
      { title: 'The Judge', artist: 'Twenty One Pilots', url: 'https://www.youtube.com/watch?v=ajiDcFKRpqQ' },
      { title: 'Stressed Out', artist: 'Twenty One Pilots', url: 'https://www.youtube.com/watch?v=pXRviuL6vMY' },
      { title: 'Vienna', artist: 'Billy Joel', url: 'https://www.youtube.com/watch?v=nDEDTFaOoMk' },
      { title: 'idontwannabeyouanymore', artist: 'Billie Eilish', url: 'https://www.youtube.com/watch?v=shy9La8MLJ0' },
      { title: 'Breathin', artist: 'Ariana Grande', url: 'https://www.youtube.com/watch?v=ndCiDpCmFts' },
      { title: 'Ribs', artist: 'Lorde', url: 'https://www.youtube.com/watch?v=SYFpEMSiokU' },
      { title: 'Buzzcut Season', artist: 'Lorde', url: 'https://www.youtube.com/watch?v=wvPiuD-ypXY' },
      { title: 'Liability', artist: 'Lorde', url: 'https://www.youtube.com/watch?v=xBqsHCMXWfU' },
      { title: 'Motion Sickness', artist: 'Phoebe Bridgers', url: 'https://www.youtube.com/watch?v=R_HMDHOJMjM' },
      { title: 'Shake It Out', artist: 'Florence + The Machine', url: 'https://www.youtube.com/watch?v=WnHtnmVqpbQ' },
      { title: 'Running with the Wolves', artist: 'Aurora', url: 'https://www.youtube.com/watch?v=QVW-OsyOB-g' },
      { title: 'Youth', artist: 'Daughter', url: 'https://www.youtube.com/watch?v=lGXlJriNjrk' },
      { title: 'Landfill', artist: 'Daughter', url: 'https://www.youtube.com/watch?v=EZNBsYXBRwY' },
      { title: 'Smother', artist: 'Daughter', url: 'https://www.youtube.com/watch?v=Km7-g-OgtBQ' },
      { title: 'All I Want', artist: 'Kodaline', url: 'https://www.youtube.com/watch?v=E0BKz6l6mEQ' },
      { title: 'Weird Fishes / Arpeggi', artist: 'Radiohead', url: 'https://www.youtube.com/watch?v=TNfgSiJC8-8' },
      { title: 'Exit Music (For a Film)', artist: 'Radiohead', url: 'https://www.youtube.com/watch?v=RDGGj3EIo6Y' },
      { title: 'Karma Police', artist: 'Radiohead', url: 'https://www.youtube.com/watch?v=1uYWYWPc9HU' },
      { title: 'About Today', artist: 'The National', url: 'https://www.youtube.com/watch?v=IgHVSMoFmis' },
      { title: 'Bloodbuzz Ohio', artist: 'The National', url: 'https://www.youtube.com/watch?v=L-ZFf2aYCac' },
      { title: 'White Flag', artist: 'Joseph', url: 'https://www.youtube.com/watch?v=0Wq8JZWV3fA' },
      { title: '4th of July', artist: 'Sufjan Stevens', url: 'https://www.youtube.com/watch?v=pDj3ikPXJkM' },
      { title: 'Clocks', artist: 'Coldplay', url: 'https://www.youtube.com/watch?v=d020hcWA_Wg' },
      { title: 'Somebody That I Used to Know', artist: 'Gotye ft. Kimbra', url: 'https://www.youtube.com/watch?v=8UVNT4wvIGY' },
      { title: 'Heavy', artist: 'Birdtalker', url: 'https://www.youtube.com/watch?v=ZFxXXpfhWtw' },
      { title: 'Electric Love', artist: 'BØRNS', url: 'https://www.youtube.com/watch?v=3lONTbFWU_4' },
    ],
    landingCard: { description: 'constant, electric, close', floatDelay: 0.2, floatDuration: 3.2, floatDistance: 8 },
  },

  content: {
    id: 'content',
    poeticName: 'Soft After Rain',
    symbol: '◌',
    tagline: 'warm, unbothered, here',
    lines: [
      'Nothing urgent. Nothing missing.',
      'The tea is still warm.',
      'This is what quiet sounds like when it means it.',
      'You have arrived, even without going anywhere.',
      'No version of right now needs fixing.',
      'You are not waiting for anything at all.',
    ],
    emotionalMetric: {
      label: 'Atmosphere',
      stages: [
        '68° settled',
        '65° fully at rest',
        '62° luminous stillness',
        '60° deep ease',
      ],
    },
    colors: {
      primary: '#C9B8FF',
      secondary: '#E8A5B5',
      accent: '#A8D8EA',
      bg: '#080610',
      text: '#E8E0FF',
      muted: 'rgba(232,224,255,0.5)',
      glow: 'rgba(201,184,255,0.28)',
      cardBg: 'rgba(201,184,255,0.07)',
      cardBorder: 'rgba(201,184,255,0.18)',
      dropdownBg: 'rgba(8,6,16,0.96)',
    },
    typography: {
      fontFamily: "'Cormorant Garamond', serif",
      weight: 300,
      letterSpacing: '0.04em',
      lineHeight: '1.9',
      style: 'italic',
    },
    interaction: {
      transitionDuration: 900,
      borderRadius: '24px',
      spacing: 'loose',
      cursorStyle: 'soft',
      textAnimation: 'drift',
      soundHook: 'rain-gentle',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'settled', intensity: 0.5 },
      { duration: 30, atmosphericLabel: 'fully at rest', intensity: 0.4 },
      { duration: 90, atmosphericLabel: 'luminous stillness', intensity: 0.3 },
      { duration: 180, atmosphericLabel: 'deep ease', intensity: 0.2 },
    ],
    playlist: [
      { title: 'Sunday Morning', artist: 'Maroon 5', url: 'https://www.youtube.com/watch?v=xufnrVxfKhU' },
      { title: 'Holocene', artist: 'Bon Iver', url: 'https://www.youtube.com/watch?v=TWcyIpul8OE' },
      { title: 'Re: Stacks', artist: 'Bon Iver', url: 'https://www.youtube.com/watch?v=Z5HTmXcnWfs' },
      { title: 'Golden Hour', artist: 'JVKE', url: 'https://www.youtube.com/watch?v=PEM0kvsP3Mw' },
      { title: 'Coffee', artist: 'beabadoobee', url: 'https://www.youtube.com/watch?v=d9I7BdBTCrs' },
      { title: 'Between the Bars', artist: 'Elliott Smith', url: 'https://www.youtube.com/watch?v=ILIfLHERmAk' },
      { title: 'Better Together', artist: 'Jack Johnson', url: 'https://www.youtube.com/watch?v=u57d4_b_YgI' },
      { title: 'Banana Pancakes', artist: 'Jack Johnson', url: 'https://www.youtube.com/watch?v=OHFvCGPWd68' },
      { title: 'Only Love', artist: 'Ben Howard', url: 'https://www.youtube.com/watch?v=guFhKaWZ3Ow' },
      { title: 'First Day of My Life', artist: 'Bright Eyes', url: 'https://www.youtube.com/watch?v=uXSTWmkSFpQ' },
      { title: 'Float On', artist: 'Modest Mouse', url: 'https://www.youtube.com/watch?v=f1OcDBklTUI' },
      { title: 'Such Great Heights', artist: 'The Postal Service', url: 'https://www.youtube.com/watch?v=0wrsZog8qXg' },
      { title: 'Golden', artist: 'Harry Styles', url: 'https://www.youtube.com/watch?v=P3cffdsEXXw' },
      { title: 'Slow Burn', artist: 'Kacey Musgraves', url: 'https://www.youtube.com/watch?v=3LZP7QHbNMk' },
      { title: 'Come Away with Me', artist: 'Norah Jones', url: 'https://www.youtube.com/watch?v=hBEAGRMI8TM' },
      { title: "Don't Know Why", artist: 'Norah Jones', url: 'https://www.youtube.com/watch?v=V4fHzrPhpbo' },
      { title: 'Falling Slowly', artist: 'Glen Hansard & Markéta Irglová', url: 'https://www.youtube.com/watch?v=pHqsZEMqrAk' },
      { title: 'Riptide', artist: 'Vance Joy', url: 'https://www.youtube.com/watch?v=uJ_1HMAGb4k' },
      { title: 'Here Comes the Sun', artist: 'The Beatles', url: 'https://www.youtube.com/watch?v=KQetemT1sWc' },
      { title: 'Let Her Go', artist: 'Passenger', url: 'https://www.youtube.com/watch?v=RBumgq5yVrA' },
      { title: 'Georgia', artist: 'Vance Joy', url: 'https://www.youtube.com/watch?v=qoFBsM1HJkE' },
      { title: 'Cherry Wine', artist: 'Hozier', url: 'https://www.youtube.com/watch?v=UHIuNXfUqXo' },
      { title: 'The Stable Song', artist: 'Gregory Alan Isakov', url: 'https://www.youtube.com/watch?v=ZdJcBwrJSaI' },
      { title: 'Pink Moon', artist: 'Nick Drake', url: 'https://www.youtube.com/watch?v=keFBeFdNZ5Y' },
      { title: 'From the Morning', artist: 'Nick Drake', url: 'https://www.youtube.com/watch?v=kVRtqMJ1t4s' },
    ],
    landingCard: { description: 'warm, unbothered, here', floatDelay: 0.5, floatDuration: 5.5, floatDistance: 12 },
  },

  happy: {
    id: 'happy',
    poeticName: 'Too Much Sun',
    symbol: '✦',
    tagline: 'bright, abundant, open',
    lines: [
      'The world leaned in and said yes.',
      'Something ordinary has become inexplicably good.',
      'Every small thing today has been quietly generous.',
      'Go ahead. Let it be this good.',
      'You keep catching yourself grinning at nothing.',
      'Even the light is trying a little harder today.',
    ],
    emotionalMetric: {
      label: 'Warmth',
      stages: [
        '89° radiant',
        '92° luminous',
        '96° overflowing',
        '98° becoming light',
      ],
    },
    colors: {
      primary: '#FFD93D',
      secondary: '#FF6B6B',
      accent: '#6BCB77',
      bg: '#100800',
      text: '#FFF5CC',
      muted: 'rgba(255,245,204,0.55)',
      glow: 'rgba(255,217,61,0.35)',
      cardBg: 'rgba(255,217,61,0.07)',
      cardBorder: 'rgba(255,217,61,0.22)',
      dropdownBg: 'rgba(20,12,0,0.96)',
    },
    typography: {
      fontFamily: "'DM Sans', sans-serif",
      weight: 300,
      letterSpacing: '0.06em',
      lineHeight: '1.7',
      style: 'normal',
    },
    interaction: {
      transitionDuration: 450,
      borderRadius: '40px',
      spacing: 'normal',
      cursorStyle: 'sparkle',
      textAnimation: 'bounce',
      soundHook: 'morning-birds',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'radiant', intensity: 0.7 },
      { duration: 30, atmosphericLabel: 'luminous', intensity: 0.8 },
      { duration: 90, atmosphericLabel: 'overflowing', intensity: 0.9 },
      { duration: 180, atmosphericLabel: 'becoming light', intensity: 1.0 },
    ],
    playlist: [
      { title: 'Good as Hell', artist: 'Lizzo', url: 'https://www.youtube.com/watch?v=SmbmeOgWsqE' },
      { title: 'About Damn Time', artist: 'Lizzo', url: 'https://www.youtube.com/watch?v=IXTBNZaSGMw' },
      { title: 'Happy', artist: 'Pharrell Williams', url: 'https://www.youtube.com/watch?v=y6Sxv-sUYtM' },
      { title: 'Levitating', artist: 'Dua Lipa', url: 'https://www.youtube.com/watch?v=TUVcZfQe-Kw' },
      { title: "Don't Start Now", artist: 'Dua Lipa', url: 'https://www.youtube.com/watch?v=oygrmJFkg68' },
      { title: 'New Rules', artist: 'Dua Lipa', url: 'https://www.youtube.com/watch?v=k2qgadSvNyU' },
      { title: "Can't Stop the Feeling!", artist: 'Justin Timberlake', url: 'https://www.youtube.com/watch?v=ru0K8uYEZWw' },
      { title: 'Walking on Sunshine', artist: 'Katrina & The Waves', url: 'https://www.youtube.com/watch?v=iPUmE-tne5U' },
      { title: 'Watermelon Sugar', artist: 'Harry Styles', url: 'https://www.youtube.com/watch?v=E07s5ZYygMg' },
      { title: 'As It Was', artist: 'Harry Styles', url: 'https://www.youtube.com/watch?v=H5v3kku2yFU' },
      { title: 'good 4 u', artist: 'Olivia Rodrigo', url: 'https://www.youtube.com/watch?v=gNi_6U5Pm_o' },
      { title: 'brutal', artist: 'Olivia Rodrigo', url: 'https://www.youtube.com/watch?v=CKNuGnqF-8E' },
      { title: 'Shake It Off', artist: 'Taylor Swift', url: 'https://www.youtube.com/watch?v=nfWlot6h_JM' },
      { title: 'Cruel Summer', artist: 'Taylor Swift', url: 'https://www.youtube.com/watch?v=ic8j13piAhQ' },
      { title: 'Mr. Brightside', artist: 'The Killers', url: 'https://www.youtube.com/watch?v=gGdGFtwCNBE' },
      { title: 'Last Nite', artist: 'The Strokes', url: 'https://www.youtube.com/watch?v=ToI1tuny9J4' },
      { title: 'Reptilia', artist: 'The Strokes', url: 'https://www.youtube.com/watch?v=1HOPAGbRmjA' },
      { title: 'September', artist: 'Earth, Wind & Fire', url: 'https://www.youtube.com/watch?v=Gs069dndIYk' },
      { title: 'Dancing Queen', artist: 'ABBA', url: 'https://www.youtube.com/watch?v=xFrGuyw1V8s' },
      { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', url: 'https://www.youtube.com/watch?v=OPf0YbXqDm0' },
      { title: 'Blinding Lights', artist: 'The Weeknd', url: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ' },
      { title: 'Electric Feel', artist: 'MGMT', url: 'https://www.youtube.com/watch?v=MmZexg8sxyk' },
      { title: 'Little Dark Age', artist: 'MGMT', url: 'https://www.youtube.com/watch?v=4UokAWWJFQs' },
      { title: 'Do I Wanna Know?', artist: 'Arctic Monkeys', url: 'https://www.youtube.com/watch?v=bpOSxM0UIJ4' },
      { title: '505', artist: 'Arctic Monkeys', url: 'https://www.youtube.com/watch?v=mxlUqkilnzs' },
      { title: 'Feel Good Inc.', artist: 'Gorillaz', url: 'https://www.youtube.com/watch?v=HyHNuVaZJ-k' },
      { title: 'Clint Eastwood', artist: 'Gorillaz', url: 'https://www.youtube.com/watch?v=1V_xRb0x9aw' },
    ],
    landingCard: { description: 'bright, abundant, open', floatDelay: 0, floatDuration: 4.0, floatDistance: 14 },
  },

  angry: {
    id: 'angry',
    poeticName: 'Teeth of a Storm',
    symbol: '⚡',
    tagline: 'sharp, charged, unspent',
    lines: [
      'This has gone on long enough.',
      'There is a word for this. And it is not fine.',
      'The patience ran out somewhere between yesterday and now.',
      'Some things deserve exactly this.',
      'You said nothing. That was the last time.',
      'Not every fire needs to be explained.',
    ],
    emotionalMetric: {
      label: 'Pressure',
      stages: [
        '108° volatile',
        '102° charged',
        '94° burning low',
        '85° residual heat',
      ],
    },
    colors: {
      primary: '#FF3A1F',
      secondary: '#FF7A00',
      accent: '#FF1744',
      bg: '#0f0100',
      text: '#FFD0C0',
      muted: 'rgba(255,208,192,0.5)',
      glow: 'rgba(255,58,31,0.4)',
      cardBg: 'rgba(255,58,31,0.08)',
      cardBorder: 'rgba(255,58,31,0.25)',
      dropdownBg: 'rgba(15,1,0,0.96)',
    },
    typography: {
      fontFamily: "'DM Sans', sans-serif",
      weight: 700,
      letterSpacing: '-0.01em',
      lineHeight: '1.3',
      style: 'normal',
    },
    interaction: {
      transitionDuration: 120,
      borderRadius: '2px',
      spacing: 'tight',
      cursorStyle: 'sharp',
      textAnimation: 'snap',
      soundHook: 'thunder-roll',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'volatile', intensity: 1.0 },
      { duration: 30, atmosphericLabel: 'charged', intensity: 0.9 },
      { duration: 90, atmosphericLabel: 'burning low', intensity: 0.7 },
      { duration: 180, atmosphericLabel: 'residual heat', intensity: 0.5 },
    ],
    playlist: [
      { title: 'Killing in the Name', artist: 'Rage Against the Machine', url: 'https://www.youtube.com/watch?v=bWXazVeUs00' },
      { title: 'Bulls on Parade', artist: 'Rage Against the Machine', url: 'https://www.youtube.com/watch?v=3L4YrGaK8ZA' },
      { title: 'Numb', artist: 'Linkin Park', url: 'https://www.youtube.com/watch?v=kXYiU_JCYtU' },
      { title: 'In the End', artist: 'Linkin Park', url: 'https://www.youtube.com/watch?v=eVTXPUF4Oz4' },
      { title: 'Crawling', artist: 'Linkin Park', url: 'https://www.youtube.com/watch?v=Gd9OhYroLN0' },
      { title: 'Given Up', artist: 'Linkin Park', url: 'https://www.youtube.com/watch?v=0xyxtzD54rM' },
      { title: 'You Oughta Know', artist: 'Alanis Morissette', url: 'https://www.youtube.com/watch?v=NPcyTyilmYY' },
      { title: 'Ironic', artist: 'Alanis Morissette', url: 'https://www.youtube.com/watch?v=Jne9t8sHpUc' },
      { title: 'Break Stuff', artist: 'Limp Bizkit', url: 'https://www.youtube.com/watch?v=ZpUYjpKg9KY' },
      { title: 'Welcome to the Black Parade', artist: 'My Chemical Romance', url: 'https://www.youtube.com/watch?v=RRKo8f_fT8I' },
      { title: 'Helena', artist: 'My Chemical Romance', url: 'https://www.youtube.com/watch?v=UCIOfj9SVlU' },
      { title: "I'm Not Okay (I Promise)", artist: 'My Chemical Romance', url: 'https://www.youtube.com/watch?v=dWe1ioNqLvo' },
      { title: 'Seven Nation Army', artist: 'The White Stripes', url: 'https://www.youtube.com/watch?v=0J2QdDbelmY' },
      { title: 'Smells Like Teen Spirit', artist: 'Nirvana', url: 'https://www.youtube.com/watch?v=hTWKbfoikeg' },
      { title: 'Come as You Are', artist: 'Nirvana', url: 'https://www.youtube.com/watch?v=vabnZ9-ex7o' },
      { title: 'Misery Business', artist: 'Paramore', url: 'https://www.youtube.com/watch?v=aCyGvGEtOwc' },
      { title: 'Ignorance', artist: 'Paramore', url: 'https://www.youtube.com/watch?v=KJm1yLX23_s' },
      { title: 'Decode', artist: 'Paramore', url: 'https://www.youtube.com/watch?v=SYaJ36P6oSk' },
      { title: 'Criminal', artist: 'Fiona Apple', url: 'https://www.youtube.com/watch?v=YTG0JBTfyGY' },
      { title: 'Paper Bag', artist: 'Fiona Apple', url: 'https://www.youtube.com/watch?v=82_bXYS0aqo' },
      { title: 'Hurt', artist: 'Nine Inch Nails', url: 'https://www.youtube.com/watch?v=OoY-eLTLiHU' },
      { title: 'Chop Suey!', artist: 'System of a Down', url: 'https://www.youtube.com/watch?v=CSvFpBOe8eY' },
      { title: 'My Own Summer (Shove It)', artist: 'Deftones', url: 'https://www.youtube.com/watch?v=-Z-Bq91kvME' },
      { title: 'Rolling in the Deep', artist: 'Adele', url: 'https://www.youtube.com/watch?v=rYEDA3JcQqw' },
      { title: 'Pumped Up Kicks', artist: 'Foster the People', url: 'https://www.youtube.com/watch?v=SDTZ7iX4vTQ' },
      { title: 'Figure 8', artist: 'Ellie Goulding', url: 'https://www.youtube.com/watch?v=M4RAFOjmRpE' },
      { title: 'Dog Days Are Over', artist: 'Florence + The Machine', url: 'https://www.youtube.com/watch?v=iWOyfLBYtuU' },
    ],
    landingCard: { description: 'sharp, charged, unspent', floatDelay: 0.1, floatDuration: 2.8, floatDistance: 6 },
  },

  sad: {
    id: 'sad',
    poeticName: 'Blue Room',
    symbol: '◉',
    tagline: 'slow, honest, wide',
    lines: [
      'Something closed without saying goodbye.',
      'The light is doing what it always does. You are not.',
      'The missing doesn\'t announce itself. It just shows up.',
      'Some days the weight doesn\'t have a shape. It just sits.',
      'You forgot for a moment. Then you remembered.',
      'A quiet that doesn\'t feel quiet at all.',
    ],
    emotionalMetric: {
      label: 'Weight',
      stages: [
        '42° heavy',
        '39° clearing slightly',
        '35° misty',
        '30° thin air',
      ],
    },
    colors: {
      primary: '#7EA8C4',
      secondary: '#5B8BA0',
      accent: '#B8D0DC',
      bg: '#060d14',
      text: '#C5D8E8',
      muted: 'rgba(197,216,232,0.5)',
      glow: 'rgba(126,168,196,0.3)',
      cardBg: 'rgba(126,168,196,0.07)',
      cardBorder: 'rgba(126,168,196,0.18)',
      dropdownBg: 'rgba(6,13,20,0.96)',
    },
    typography: {
      fontFamily: "'Cormorant Garamond', serif",
      weight: 300,
      letterSpacing: '0.06em',
      lineHeight: '2.0',
      style: 'normal',
    },
    interaction: {
      transitionDuration: 1100,
      borderRadius: '16px',
      spacing: 'loose',
      cursorStyle: 'blur',
      textAnimation: 'fade',
      soundHook: 'rain-heavy',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'heavy', intensity: 0.9 },
      { duration: 30, atmosphericLabel: 'clearing slightly', intensity: 0.75 },
      { duration: 90, atmosphericLabel: 'misty', intensity: 0.55 },
      { duration: 180, atmosphericLabel: 'thin air', intensity: 0.35 },
    ],
    playlist: [
      { title: 'The Night We Met', artist: 'Lord Huron', url: 'https://www.youtube.com/watch?v=KtlgYxa6BMU' },
      { title: 'Ends of the Earth', artist: 'Lord Huron', url: 'https://www.youtube.com/watch?v=OVuJE68tOzc' },
      { title: 'Skinny Love', artist: 'Bon Iver', url: 'https://www.youtube.com/watch?v=ssdgFoHLwnk' },
      { title: 'Someone Like You', artist: 'Adele', url: 'https://www.youtube.com/watch?v=hLQl3WQQoQ0' },
      { title: 'Hello', artist: 'Adele', url: 'https://www.youtube.com/watch?v=YQHsXMglC9A' },
      { title: 'drivers license', artist: 'Olivia Rodrigo', url: 'https://www.youtube.com/watch?v=ZmDBbnmKpqQ' },
      { title: 'traitor', artist: 'Olivia Rodrigo', url: 'https://www.youtube.com/watch?v=dag7Y4vIJXI' },
      { title: 'The Scientist', artist: 'Coldplay', url: 'https://www.youtube.com/watch?v=RB-RcX5DS5A' },
      { title: 'Fix You', artist: 'Coldplay', url: 'https://www.youtube.com/watch?v=k4V3Mo61fJM' },
      { title: 'Savior Complex', artist: 'Phoebe Bridgers', url: 'https://www.youtube.com/watch?v=3Td_RtSwKzw' },
      { title: 'Garden Song', artist: 'Phoebe Bridgers', url: 'https://www.youtube.com/watch?v=SvvxcKbqtqI' },
      { title: 'Funeral', artist: 'Phoebe Bridgers', url: 'https://www.youtube.com/watch?v=4cuaAkBxGMM' },
      { title: 'Casimir Pulaski Day', artist: 'Sufjan Stevens', url: 'https://www.youtube.com/watch?v=f8Ux77U_5jg' },
      { title: 'Death With Dignity', artist: 'Sufjan Stevens', url: 'https://www.youtube.com/watch?v=UiNbVyAiuJo' },
      { title: 'Fast Car', artist: 'Tracy Chapman', url: 'https://www.youtube.com/watch?v=AIOAlaAuLR8' },
      { title: 'Blackbird', artist: 'The Beatles', url: 'https://www.youtube.com/watch?v=Man4Xw8Sza8' },
      { title: 'Eleanor Rigby', artist: 'The Beatles', url: 'https://www.youtube.com/watch?v=HuS5NuXRb5Y' },
      { title: 'Mad World', artist: 'Gary Jules', url: 'https://www.youtube.com/watch?v=4N3N1MlvVc4' },
      { title: 'Black', artist: 'Pearl Jam', url: 'https://www.youtube.com/watch?v=fjBSgFaJc-o' },
      { title: 'Lua', artist: 'Bright Eyes', url: 'https://www.youtube.com/watch?v=n_MiAPlGwkY' },
      { title: 'Hurt', artist: 'Johnny Cash', url: 'https://www.youtube.com/watch?v=8AHCfZTRGiI' },
      { title: 'Fake Plastic Trees', artist: 'Radiohead', url: 'https://www.youtube.com/watch?v=XFkzRNyygfk' },
      { title: 'Let Down', artist: 'Radiohead', url: 'https://www.youtube.com/watch?v=EBs_YvRZ9cs' },
      { title: 'Landslide', artist: 'Fleetwood Mac', url: 'https://www.youtube.com/watch?v=WM7-PYoEPNE' },
      { title: 'Linger', artist: 'The Cranberries', url: 'https://www.youtube.com/watch?v=gYF66Zb0MwI' },
      { title: 'I Will Follow You into the Dark', artist: 'Death Cab for Cutie', url: 'https://www.youtube.com/watch?v=s-qC46cVCFM' },
      { title: 'Colorblind', artist: 'Counting Crows', url: 'https://www.youtube.com/watch?v=Qc5zHbCGYWs' },
    ],
    landingCard: { description: 'slow, honest, wide', floatDelay: 0.7, floatDuration: 6.0, floatDistance: 10 },
  },

  hopeful: {
    id: 'hopeful',
    poeticName: 'Almost Becoming',
    symbol: '↑',
    tagline: 'rising, unfinished, tender',
    lines: [
      'Something is gathering at the edges.',
      "It hasn't arrived yet. But it's on its way.",
      'The window is the same window. The view is different.',
      'There is space, now, where something good could grow.',
      'Small things are adding up to something.',
      'You can feel the direction, even if you can\'t see the road yet.',
    ],
    emotionalMetric: {
      label: 'Visibility',
      stages: [
        '22° dim but present',
        '45° emerging',
        '68° golden hour',
        '88° clear',
      ],
    },
    colors: {
      primary: '#FFB347',
      secondary: '#FF8C69',
      accent: '#FFDB89',
      bg: '#080510',
      text: '#FFF0D0',
      muted: 'rgba(255,240,208,0.5)',
      glow: 'rgba(255,179,71,0.35)',
      cardBg: 'rgba(255,179,71,0.08)',
      cardBorder: 'rgba(255,179,71,0.22)',
      dropdownBg: 'rgba(8,5,16,0.96)',
    },
    typography: {
      fontFamily: "'Cormorant Garamond', serif",
      weight: 400,
      letterSpacing: '0.05em',
      lineHeight: '1.8',
      style: 'normal',
    },
    interaction: {
      transitionDuration: 700,
      borderRadius: '20px',
      spacing: 'normal',
      cursorStyle: 'ember',
      textAnimation: 'rise',
      soundHook: 'dawn-birds',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'dim but present', intensity: 0.4 },
      { duration: 30, atmosphericLabel: 'emerging', intensity: 0.6 },
      { duration: 90, atmosphericLabel: 'golden hour', intensity: 0.8 },
      { duration: 180, atmosphericLabel: 'clear', intensity: 1.0 },
    ],
    playlist: [
      { title: 'Here Comes the Sun', artist: 'The Beatles', url: 'https://www.youtube.com/watch?v=KQetemT1sWc' },
      { title: 'Let It Be', artist: 'The Beatles', url: 'https://www.youtube.com/watch?v=QDYfEBY9NM4' },
      { title: 'Dog Days Are Over', artist: 'Florence + The Machine', url: 'https://www.youtube.com/watch?v=iWOyfLBYtuU' },
      { title: 'The Story', artist: 'Brandi Carlile', url: 'https://www.youtube.com/watch?v=HuBWPGbXBLs' },
      { title: 'Better Days', artist: 'OneRepublic', url: 'https://www.youtube.com/watch?v=VHrLPs3_1Fs' },
      { title: 'Glorious', artist: 'Macklemore ft. Skylar Grey', url: 'https://www.youtube.com/watch?v=lqDonas-LSE' },
      { title: 'Keep Your Head Up', artist: 'Ben Howard', url: 'https://www.youtube.com/watch?v=gOKTXMgDMjw' },
      { title: 'Rivers and Roads', artist: 'The Head and the Heart', url: 'https://www.youtube.com/watch?v=PEGi6P6TuTQ' },
      { title: 'Lost in My Mind', artist: 'The Head and the Heart', url: 'https://www.youtube.com/watch?v=-3Ygf1Z9LmE' },
      { title: 'Home', artist: 'Phillip Phillips', url: 'https://www.youtube.com/watch?v=HoRkntoHkIE' },
      { title: 'You Are the Best Thing', artist: 'Ray LaMontagne', url: 'https://www.youtube.com/watch?v=5DFqzxCvAas' },
      { title: 'Trouble', artist: 'Ray LaMontagne', url: 'https://www.youtube.com/watch?v=JbiENwg0Fcs' },
      { title: 'Rainbow', artist: 'Kacey Musgraves', url: 'https://www.youtube.com/watch?v=7NBHSUaJkSE' },
      { title: 'Golden Hour', artist: 'Kacey Musgraves', url: 'https://www.youtube.com/watch?v=3d8l2Ip6qQs' },
      { title: 'A Sky Full of Stars', artist: 'Coldplay', url: 'https://www.youtube.com/watch?v=6Cf7IL_eZ38' },
      { title: 'Yellow', artist: 'Coldplay', url: 'https://www.youtube.com/watch?v=yKNxeF4KMsY' },
      { title: 'Beautiful Day', artist: 'U2', url: 'https://www.youtube.com/watch?v=co6WMzDkh7Y' },
      { title: 'Light', artist: 'Sleeping at Last', url: 'https://www.youtube.com/watch?v=c1sMbFRDRk0' },
      { title: 'Saturn', artist: 'Sleeping at Last', url: 'https://www.youtube.com/watch?v=dzNvk80XbUQ' },
      { title: 'Dare You to Move', artist: 'Switchfoot', url: 'https://www.youtube.com/watch?v=_0oFMGrGYk8' },
      { title: 'Take Me to Church', artist: 'Hozier', url: 'https://www.youtube.com/watch?v=MYSVMgRr6pw' },
      { title: 'Turning Tables', artist: 'Adele', url: 'https://www.youtube.com/watch?v=GXBC7NcTuBE' },
      { title: 'Still Fighting It', artist: 'Ben Folds', url: 'https://www.youtube.com/watch?v=7Y63eTBxgKA' },
      { title: 'Stubborn Love', artist: 'The Lumineers', url: 'https://www.youtube.com/watch?v=krkWHvLNNrk' },
      { title: 'Ho Hey', artist: 'The Lumineers', url: 'https://www.youtube.com/watch?v=zvCBSSwmwdI' },
      { title: 'Flowers in Your Hair', artist: 'The Lumineers', url: 'https://www.youtube.com/watch?v=NZSM2WTkiAg' },
    ],
    landingCard: { description: 'rising, unfinished, tender', floatDelay: 0.3, floatDuration: 4.8, floatDistance: 16 },
  },

  mysterious: {
    id: 'mysterious',
    poeticName: 'Velvet Dark',
    symbol: '◈',
    tagline: 'deep, unnamed, possible',
    lines: [
      'Not everything that watches you means harm.',
      'The map is wrong. The territory is more interesting.',
      'You have been here before, in some form.',
      "There is a name for what you're feeling. It hasn't been invented yet.",
      'The answer keeps changing shape.',
      'Something here knows you. You are still figuring out what.',
    ],
    emotionalMetric: {
      label: 'Depth',
      stages: [
        'unknown° immeasurable',
        'unknown° expanding',
        '∞° folding inward',
        '∞° uncharted',
      ],
    },
    colors: {
      primary: '#A855F7',
      secondary: '#3B82F6',
      accent: '#EC4899',
      bg: '#020208',
      text: '#E0D0FF',
      muted: 'rgba(224,208,255,0.48)',
      glow: 'rgba(168,85,247,0.35)',
      cardBg: 'rgba(168,85,247,0.07)',
      cardBorder: 'rgba(168,85,247,0.2)',
      dropdownBg: 'rgba(2,2,8,0.98)',
    },
    typography: {
      fontFamily: "'Cormorant Garamond', serif",
      weight: 400,
      letterSpacing: '0.12em',
      lineHeight: '1.85',
      style: 'normal',
    },
    interaction: {
      transitionDuration: 800,
      borderRadius: '12px',
      spacing: 'normal',
      cursorStyle: 'reveal',
      textAnimation: 'breathe',
      soundHook: 'cosmic-hum',
    },
    evolution: [
      { duration: 0, atmosphericLabel: 'immeasurable', intensity: 0.6 },
      { duration: 30, atmosphericLabel: 'expanding', intensity: 0.7 },
      { duration: 90, atmosphericLabel: 'folding inward', intensity: 0.8 },
      { duration: 180, atmosphericLabel: 'uncharted', intensity: 0.9 },
    ],
    playlist: [
      { title: 'Space Song', artist: 'Beach House', url: 'https://www.youtube.com/watch?v=3yfBKFaD0nE' },
      { title: 'Myth', artist: 'Beach House', url: 'https://www.youtube.com/watch?v=YLsIHHHFQGs' },
      { title: 'Silver Soul', artist: 'Beach House', url: 'https://www.youtube.com/watch?v=L2FMi3-PKSY' },
      { title: 'Midnight City', artist: 'M83', url: 'https://www.youtube.com/watch?v=dX3k_QDnzHE' },
      { title: 'Outro', artist: 'M83', url: 'https://www.youtube.com/watch?v=lyCpBqVr-0E' },
      { title: 'Fade Into You', artist: 'Mazzy Star', url: 'https://www.youtube.com/watch?v=AxMOEeEOcIw' },
      { title: 'Into Dust', artist: 'Mazzy Star', url: 'https://www.youtube.com/watch?v=xvqeDTMrfBk' },
      { title: 'Teardrop', artist: 'Massive Attack', url: 'https://www.youtube.com/watch?v=cy-Em6DzCvI' },
      { title: 'Unfinished Sympathy', artist: 'Massive Attack', url: 'https://www.youtube.com/watch?v=0oSBkCsHkJ4' },
      { title: 'Glory Box', artist: 'Portishead', url: 'https://www.youtube.com/watch?v=uFmBit6jB4o' },
      { title: 'Sour Times', artist: 'Portishead', url: 'https://www.youtube.com/watch?v=0JJoeLBhtqQ' },
      { title: 'Experience', artist: 'Ludovico Einaudi', url: 'https://www.youtube.com/watch?v=hN_q-_nGv4U' },
      { title: 'Riders on the Storm', artist: 'The Doors', url: 'https://www.youtube.com/watch?v=iv8GW1GaoqA' },
      { title: 'People Are Strange', artist: 'The Doors', url: 'https://www.youtube.com/watch?v=sKLmJOAJKYk' },
      { title: 'Comfortably Numb', artist: 'Pink Floyd', url: 'https://www.youtube.com/watch?v=_FrOQC-zEog' },
      { title: 'Wish You Were Here', artist: 'Pink Floyd', url: 'https://www.youtube.com/watch?v=IXdNnw99-Ic' },
      { title: 'Where Is My Mind?', artist: 'Pixies', url: 'https://www.youtube.com/watch?v=GqE9YRYs3h4' },
      { title: 'Something in the Way', artist: 'Nirvana', url: 'https://www.youtube.com/watch?v=kGMEq64SVGQ' },
      { title: 'California Dreamin\'', artist: 'The Mamas & The Papas', url: 'https://www.youtube.com/watch?v=N-aK6JnyFmk' },
      { title: 'Dream a Little Dream of Me', artist: 'Ella Fitzgerald', url: 'https://www.youtube.com/watch?v=7e-eDRGKezg' },
      { title: 'Laura Palmer', artist: 'Bastille', url: 'https://www.youtube.com/watch?v=PDKhB7BOAFU' },
      { title: 'Pompeii', artist: 'Bastille', url: 'https://www.youtube.com/watch?v=F90Cw4l-8NY' },
      { title: 'Strange', artist: 'Celeste', url: 'https://www.youtube.com/watch?v=W0-dRxjQb3g' },
      { title: 'In My Room', artist: 'The Beach Boys', url: 'https://www.youtube.com/watch?v=QlAGKQH2JvI' },
      { title: 'Sound of Silence', artist: 'Simon & Garfunkel', url: 'https://www.youtube.com/watch?v=4fWyzwo1xg0' },
      { title: 'Breathe', artist: 'Pink Floyd', url: 'https://www.youtube.com/watch?v=3UP_hhSPb00' },
      { title: 'Falling', artist: 'Harry Styles', url: 'https://www.youtube.com/watch?v=ry0GQPUkDIo' },
    ],
    landingCard: { description: 'deep, unnamed, possible', floatDelay: 0.6, floatDuration: 5.2, floatDistance: 11 },
  },
};

export const MOOD_IDS: string[] = Object.keys(MOODS);
export default MOODS;
